version: "3.9"
services:
  web:
    image: seed-web
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    env_file:
      - app.env
    depends_on:
      - db
    links:
      - db
    networks:
      - seed-net

  crawler:
      image: seed-crawler
      build:
        context: ./crawler
        dockerfile: Dockerfile
      restart: always
      env_file:
        - app.env
      depends_on:
        - db
      links:
        - db
      networks:
        - seed-net

  db:
    image: postgres:14
    platform: linux/x86_64
    restart: always
    ports:
      - "5431:5432"
    env_file:
      - app.env
    volumes:
      - "~/Docker/blog/data:/var/lib/postgresql/data"
      - "./data:/var/lib/postgresql/data"
    networks:
      - seed-net

  nginx:
      image: nginx:latest
      volumes:
        - ./config/nginx:/etc/nginx/conf.d/
      ports:
        - "80:80"
      depends_on:
        - db
        - web
        - pgbouncer
      networks:
        - seed-net

#  adminer:
#    image: adminer
#    platform: linux/x86_64
#    restart: always
#    ports:
#      - "8081:8080"
#    networks:
#      - seed-net

  pgbouncer:
    image: edoburu/pgbouncer
    platform: linux/x86_64
    volumes:
      - ./conf:/etc/pgbouncer
    env_file:
      - app.env
    ports:
      - "6432:6432"
    depends_on:
      - db
    networks:
      - seed-net


volumes:
  db:
  config:
  data:

networks:
  seed-net:
       