# Generated by Django 4.1.1 on 2023-12-10 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('video_link', models.TextField(blank=True, null=True)),
                ('video_image', models.TextField(blank=True, null=True)),
                ('video_length', models.CharField(max_length=255)),
                ('video_title', models.TextField(blank=True, null=True)),
                ('video_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_day', models.DateField(auto_now_add=True)),
                ('video_keyword', models.TextField(blank=True, null=True)),
                ('video_quality', models.IntegerField(default=0)),
                ('video_url', models.TextField(blank=True, null=True)),
                ('video_source', models.CharField(max_length=255)),
                ('video_recomend', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
