# Generated by Django 4.1.1 on 2022-12-20 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="createdAt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="video",
            name="deletedAt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="video",
            name="updatedAt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
