# Generated by Django 4.1.1 on 2022-12-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0002_video_createdat_video_deletedat_video_updatedat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="deletedAt",
            field=models.DateTimeField(default=None),
        ),
    ]
