# Generated by Django 4.1.1 on 2022-12-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0003_alter_video_deletedat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="deletedAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
