# Generated by Django 4.1.1 on 2022-12-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0004_alter_video_deletedat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_keyword",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
